### PR TITLE
Calculated Policy - AWS Default Tagging

### LINKED ISSUE #303: Calculated Policy - AWS Default Tagging
https://github.com/turbot/tdk/pull/296

### PR DESCRIPTION
**Pull request by choxie**
Calculated policy that applies tags to all resources under Turbot management.

closes #303

### CODE REVIEW

**Comment by omerosaienni** [comment]
No issue linked

**Review by omerosaienni — CHANGES_REQUESTED** [review]
Issue with PR

**Review by omerosaienni — CHANGES_REQUESTED** [review]
PR request issue

**Comment by choxie** [comment]
closes https://github.com/turbot/tdk/issues/303

**Pull request closed without merging**
