### PR TITLE
Control Objective - Fix title for AWS EC2 - Restrict Instance images to trusted AWS accounts AMIs #301

### LINKED ISSUE #301: Control Objective - Fix title for AWS EC2 - Restrict Instance images to trusted AWS accounts AMIs
https://github.com/turbot/tdk/pull/291

### PR DESCRIPTION
**Pull request by choxie**
closes #301

### CODE REVIEW

**Comment by omerosaienni** [comment]
No issue linked

**Review by omerosaienni — CHANGES_REQUESTED** [review]
No linked PR

**Comment by choxie** [comment]
closes https://github.com/turbot/tdk/issues/301

**Comment by omerosaienni** [comment]
Hi @choxie 

If you want to change the title, it is done in the template

`./repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_approved_account_ami/template.yml`

Then you have to run the documentation generator

You can see that in the `./package.json`

```json
{
  "name": "repo-tools",
  "version": "1.0.0",
  "description": "Document generation scripts to keep documentation uniformity for differing TDK example types.",
  "scripts": {
    "gen-doc": "npm run gen-doc:calc-policies && npm run gen-doc:api-examples",
    "gen-doc:calc-policies": "node gen-doc-calc-policies.js",
    "gen-doc:api-examples": "node gen-doc-api-examples.js"
  },
  "author": "Turbot HQ, Inc",
  "license": "ISC",
  "dependencies": {
    "chalk": "^4.0.0",
    "js-yaml": "^3.13.1",
    "moment": "^2.26.0",
    "nunjucks": "^3.2.1"
  }
}
```

**Review by omerosaienni — APPROVED** [review]

**Pull request merged**
