### PR TITLE
Baseline - Refactor GCP check encryption #385

### LINKED ISSUE #385: Baseline - Refactor GCP check encryption
- [x] Create README.md
- [x] Add outputs.tf
- [x] Add variables.tf
- [x] Add providers.tf
- [x] Add smart_folder.tf
- [x] Categories polices
- [x] Add guardrail (category) links
- [x] Add mod links
- [ ] Refactor to be in sync with baselines

### PR DESCRIPTION
**Pull request by krishna5891**
Closes #385

### CODE REVIEW

**Comment by krishna5891** [comment]
```
krishna@turbotindias-MacBook-Pro gcp_check_encryption % terraform apply  
var.turbot_profile
  Enter profile matching your turbot cli credentials.

  Enter a value: punisher


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # turbot_policy_setting.gcp_bigquery_dataset_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_bigquery_dataset_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-bigquery#/policy/types/datasetApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_bigquery_dataset_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_bigquery_dataset_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-bigquery#/policy/types/datasetApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_bigquery_table_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_bigquery_table_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-bigquery#/policy/types/tableApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_bigquery_table_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_bigquery_table_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-bigquery#/policy/types/tableApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_computeengine_disk_approved will be created
  + resource "turbot_policy_setting" "gcp_computeengine_disk_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-computeengine#/policy/types/diskApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_computeengine_disk_approved_encryption_at_rest will be created
  + resource "turbot_policy_setting" "gcp_computeengine_disk_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-computeengine#/policy/types/diskApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_computeengine_image_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_computeengine_image_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-computeengine#/policy/types/imageApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_computeengine_image_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_computeengine_image_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-computeengine#/policy/types/imageApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_dataflow_job_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_dataflow_job_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-dataflow#/policy/types/jobApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_dataflow_job_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_dataflow_job_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-dataflow#/policy/types/jobApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_dataproc_cluster_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_dataproc_cluster_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-dataproc#/policy/types/clusterApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_dataproc_cluster_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_dataproc_cluster_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-dataproc#/policy/types/clusterApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_kubernetesengine_region_cluster_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_kubernetesengine_region_cluster_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-kubernetesengine#/policy/types/regionClusterApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_kubernetesengine_region_cluster_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_kubernetesengine_region_cluster_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-kubernetesengine#/policy/types/regionClusterApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_kubernetesengine_zone_cluster_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_kubernetesengine_zone_cluster_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-kubernetesengine#/policy/types/zoneClusterApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_kubernetesengine_zone_cluster_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_kubernetesengine_zone_cluster_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-kubernetesengine#/policy/types/zoneClusterApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_pubsub_topic_approved[0] will be created
  + resource "turbot_policy_setting" "gcp_pubsub_topic_approved" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-pubsub#/policy/types/topicApproved"
      + value                        = "Check: Approved"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_pubsub_topic_approved_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_pubsub_topic_approved_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-pubsub#/policy/types/topicApprovedEncryptionAtRest"
      + value                        = "Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_policy_setting.gcp_storage_bucket_encryption_at_rest[0] will be created
  + resource "turbot_policy_setting" "gcp_storage_bucket_encryption_at_rest" {
      + id                           = (known after apply)
      + precedence                   = "REQUIRED"
      + resource                     = (known after apply)
      + resource_akas                = (known after apply)
      + type                         = "tmod:@turbot/gcp-storage#/policy/types/bucketEncryptionAtRest"
      + value                        = "Check: Google managed key"
      + value_key_fingerprint        = (known after apply)
      + value_source                 = (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }

  # turbot_smart_folder.gcp_encryption will be created
  + resource "turbot_smart_folder" "gcp_encryption" {
      + description = "Defines sets of policies for the GCP Check Encryption"
      + id          = (known after apply)
      + parent      = "tmod:@turbot/turbot#/"
      + parent_akas = (known after apply)
      + title       = "GCP Check Encryption Policies"
    }

Plan: 20 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + enable_bigquery_dataset_approved_encryption_at_rest_policies                = true
  + enable_bigquery_dataset_approved_policies                                   = true
  + enable_bigquery_table_approved_encryption_at_rest_policies                  = true
  + enable_bigquery_table_approved_policies                                     = true
  + enable_computeengine_image_approved_encryption_at_rest_policies             = true
  + enable_computeengine_image_approved_policies                                = true
  + enable_dataflow_job_approved_encryption_at_rest_policies                    = true
  + enable_dataflow_job_approved_policies                                       = true
  + enable_dataproc_cluster_approved_encryption_at_rest_policies                = true
  + enable_dataproc_cluster_approved_policies                                   = true
  + enable_kubernetesengine_region_cluster_approved_encryption_at_rest_policies = true
  + enable_kubernetesengine_region_cluster_approved_policies                    = true
  + enable_kubernetesengine_zone_cluster_approved_encryption_at_rest_policies   = true
  + enable_kubernetesengine_zone_cluster_approved_policies                      = true
  + enable_pubsub_topic_approved_encryption_at_rest_policies                    = true
  + enable_pubsub_topic_approved_policies                                       = true
  + enable_storage_bucket_encryption_at_rest_policies                           = true
  + smart_folder_description                                                    = "Defines sets of policies for the GCP Check Encryption"
  + smart_folder_name                                                           = "GCP Check Encryption Policies"
  + smart_folder_parent_resource                                                = "tmod:@turbot/turbot#/"
  + turbot_profile                                                              = "punisher"

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

turbot_smart_folder.gcp_encryption: Creating...
turbot_smart_folder.gcp_encryption: Creation complete after 2s [id=216620005119805]
turbot_policy_setting.gcp_computeengine_disk_approved: Creating...
turbot_policy_setting.gcp_kubernetesengine_zone_cluster_approved[0]: Creating...
turbot_policy_setting.gcp_dataflow_job_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_storage_bucket_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_pubsub_topic_approved[0]: Creating...
turbot_policy_setting.gcp_kubernetesengine_zone_cluster_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_bigquery_dataset_approved[0]: Creating...
turbot_policy_setting.gcp_pubsub_topic_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_computeengine_disk_approved_encryption_at_rest: Creating...
turbot_policy_setting.gcp_computeengine_image_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_dataflow_job_approved_encryption_at_rest[0]: Creation complete after 3s [id=216620008804618]
turbot_policy_setting.gcp_storage_bucket_encryption_at_rest[0]: Creation complete after 3s [id=216620008714491]
turbot_policy_setting.gcp_kubernetesengine_region_cluster_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_bigquery_dataset_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_kubernetesengine_zone_cluster_approved_encryption_at_rest[0]: Creation complete after 5s [id=216620009104701]
turbot_policy_setting.gcp_computeengine_disk_approved_encryption_at_rest: Creation complete after 5s [id=216620009940338]
turbot_policy_setting.gcp_bigquery_dataset_approved[0]: Creation complete after 5s [id=216620008743165]
turbot_policy_setting.gcp_bigquery_table_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_dataproc_cluster_approved[0]: Creating...
turbot_policy_setting.gcp_dataflow_job_approved[0]: Creating...
turbot_policy_setting.gcp_kubernetesengine_region_cluster_approved_encryption_at_rest[0]: Creation complete after 3s [id=216620011822615]
turbot_policy_setting.gcp_computeengine_image_approved_encryption_at_rest[0]: Creation complete after 6s [id=216620011643397]
turbot_policy_setting.gcp_pubsub_topic_approved[0]: Creation complete after 6s [id=216620009378138]
turbot_policy_setting.gcp_computeengine_image_approved[0]: Creating...
turbot_policy_setting.gcp_pubsub_topic_approved_encryption_at_rest[0]: Creation complete after 6s [id=216620010634660]
turbot_policy_setting.gcp_computeengine_disk_approved: Creation complete after 6s [id=216620010336647]
turbot_policy_setting.gcp_kubernetesengine_zone_cluster_approved[0]: Creation complete after 6s [id=216620010821054]
turbot_policy_setting.gcp_dataproc_cluster_approved_encryption_at_rest[0]: Creating...
turbot_policy_setting.gcp_bigquery_table_approved[0]: Creating...
turbot_policy_setting.gcp_kubernetesengine_region_cluster_approved[0]: Creating...
turbot_policy_setting.gcp_bigquery_dataset_approved_encryption_at_rest[0]: Creation complete after 4s [id=216620012640835]
turbot_policy_setting.gcp_dataflow_job_approved[0]: Creation complete after 2s [id=216620013475413]
turbot_policy_setting.gcp_bigquery_table_approved_encryption_at_rest[0]: Creation complete after 2s [id=216620013339212]
turbot_policy_setting.gcp_dataproc_cluster_approved[0]: Creation complete after 2s [id=216620013472338]
turbot_policy_setting.gcp_dataproc_cluster_approved_encryption_at_rest[0]: Creation complete after 2s [id=216620014050908]
turbot_policy_setting.gcp_computeengine_image_approved[0]: Creation complete after 2s [id=216620014179943]
turbot_policy_setting.gcp_kubernetesengine_region_cluster_approved[0]: Creation complete after 2s [id=216620014126689]
turbot_policy_setting.gcp_bigquery_table_approved[0]: Creation complete after 2s [id=216620014179942]

Apply complete! Resources: 20 added, 0 changed, 0 destroyed.

Outputs:

enable_bigquery_dataset_approved_encryption_at_rest_policies = true
enable_bigquery_dataset_approved_policies = true
enable_bigquery_table_approved_encryption_at_rest_policies = true
enable_bigquery_table_approved_policies = true
enable_computeengine_image_approved_encryption_at_rest_policies = true
enable_computeengine_image_approved_policies = true
enable_dataflow_job_approved_encryption_at_rest_policies = true
enable_dataflow_job_approved_policies = true
enable_dataproc_cluster_approved_encryption_at_rest_policies = true
enable_dataproc_cluster_approved_policies = true
enable_kubernetesengine_region_cluster_approved_encryption_at_rest_policies = true
enable_kubernetesengine_region_cluster_approved_policies = true
enable_kubernetesengine_zone_cluster_approved_encryption_at_rest_policies = true
enable_kubernetesengine_zone_cluster_approved_policies = true
enable_pubsub_topic_approved_encryption_at_rest_policies = true
enable_pubsub_topic_approved_policies = true
enable_storage_bucket_encryption_at_rest_policies = true
smart_folder_description = Defines sets of policies for the GCP Check Encryption
smart_folder_name = GCP Check Encryption Policies
smart_folder_parent_resource = tmod:@turbot/turbot#/
turbot_profile = punisher

**Review by omerosaienni — APPROVED** [review]

**Comment by omerosaienni** [comment]
Code okay. 

Post release test not done yet.

**Review by omerosaienni — COMMENTED** [review]
Need to test

**Review by omerosaienni — CHANGES_REQUESTED** [review]
Unapproving until I test

**Comment by rajmohanty17** [comment]
> Unapproving until I test

image

**Pull request merged**
