### PR TITLE
Calculated Policy - AWS EC2 Approve Cross Account Access for AMI and Snapshots

### LINKED ISSUE #304: Calculated Policy - AWS EC2 Approve Cross Account Access for AMI and Snapshots

### PR DESCRIPTION
**Pull request by choxie**
closes #304

### CODE REVIEW

**Comment by omerosaienni** [comment]
No issue linked.

**Review by omerosaienni — COMMENTED** [review]
Issue with PR

**Review by omerosaienni — CHANGES_REQUESTED** [review]
Issue with PR

**Review by omerosaienni — CHANGES_REQUESTED** [review]
Issue with PR

**Comment by choxie** [comment]
closes https://github.com/turbot/tdk/issues/304

**Pull request closed without merging**
