### PR TITLE
Calculated Policy - Example folder structure using Terraform #305

### LINKED ISSUE #305: Example folder structure using Terraform
https://github.com/turbot/tdk/pull/298

### PR DESCRIPTION
**Pull request by choxie**
closes #305

### CODE REVIEW

**Comment by omerosaienni** [comment]
No issue, waiting on this.

**Review by omerosaienni — CHANGES_REQUESTED** [review]
Issue with PR

**Comment by choxie** [comment]
closes https://github.com/turbot/tdk/issues/305

**Review by omerosaienni — CHANGES_REQUESTED** [review]
You have two different changes in this PR, you have a folders example and then you have cross account snapshot stuff. 

Please separate this out into two Issues, link the PR with the `closes` command and if you can in the issue, provide me details as to why we are doing this and what we want to accomplish?

**Review by omerosaienni — APPROVED** [review]

**Pull request merged**
